# Generated by Django 6.1.1 on 2026-09-28 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand_type', models.CharField(choices=[('personal', 'Personal Brand'), ('business', 'Business'), ('creator', 'Creator'), ('freelancer', 'Freelancer'), ('startup', 'Startup'), ('agency', 'Agency'), ('organization', 'Organization'), ('other', 'Other')], max_length=30)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('niche', models.CharField(blank=True, max_length=100)),
                ('target_audience', models.JSONField(blank=True, default=list)),
                ('primary_goal', models.CharField(blank=True, choices=[('grow_audience', 'Grow my audience'), ('build_authority', 'Build authority'), ('get_clients', 'Get clients'), ('generate_leads', 'Generate leads'), ('sell_products', 'Sell products'), ('personal_brand', 'Build a personal brand'), ('engagement', 'Increase engagement'), ('not_sure', "I'm not sure yet")], max_length=40)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('additional_information', models.TextField(blank=True, help_text='Tell Workbeam anything else about your brand, audience, story, products, personality or goals.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('import', 'Import'), ('website', 'Website'), ('social', 'Social Media')], default='user', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='brands.brand')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
