# Generated by Django 6.1.1 on 2026-09-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_brand_platforms_alter_brand_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandknowledge',
            name='knowledge_type',
            field=models.CharField(choices=[('story', 'Brand Story'), ('audience', 'Audience'), ('product', 'Products & Services'), ('voice', 'Brand Voice'), ('expertise', 'Expertise'), ('content', 'Content Preferences'), ('goal', 'Goals'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
