# Generated by Django 6.1.1 on 2026-10-03 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brands", "0003_brandknowledge_knowledge_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("raw_content", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-collected_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("connected", "Connected to Brand"),
                            ("independent", "Independent Research"),
                        ],
                        default="independent",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "research_brief",
                    models.TextField(
                        help_text="Describe what you want Workbeam to research."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("researching", "Researching"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_sessions",
                        to="brands.brand",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("topic", "Topic"),
                            ("problem", "Problem"),
                            ("question", "Question"),
                            ("trend", "Trend"),
                            ("desire", "Desire"),
                            ("objection", "Objection"),
                            ("competitor_activity", "Competitor Activity"),
                            ("content_pattern", "Content Pattern"),
                            ("audience_insight", "Audience Insight"),
                            ("opportunity_signal", "Opportunity Signal"),
                        ],
                        max_length=40,
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=255)),
                ("finding", models.TextField()),
                ("audience", models.TextField(blank=True)),
                ("evidence", models.TextField(blank=True)),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "research_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="research.researchitem",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="research.researchsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("linkedin", "LinkedIn"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="research.researchsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="researchitem",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="research.researchsource",
            ),
        ),
    ]
