# Generated by Django 6.1.1 on 2026-10-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsession',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
