# Generated by Django 6.1.1 on 2026-10-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_researchsession_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsession',
            name='depth',
            field=models.CharField(choices=[('quick', 'Quick'), ('standard', 'Standard'), ('deep', 'Deep')], default='standard', max_length=20),
        ),
    ]
