# Generated by Django 6.1.1 on 2026-10-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_researchsession_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrun',
            name='queries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
