# Generated by Django 6.1.1 on 2026-10-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_researchrun_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrun',
            name='stage',
            field=models.CharField(choices=[('planning', 'Planning research'), ('searching', 'Searching'), ('collecting', 'Collecting evidence'), ('analyzing', 'Analyzing evidence'), ('building', 'Building intelligence'), ('completed', 'Research complete'), ('failed', 'Research failed')], default='planning', max_length=20),
        ),
        migrations.AddField(
            model_name='researchrun',
            name='stage_message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
