# Generated by Django 6.1.1 on 2026-10-07 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_researchrun_stage_researchrun_stage_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_runs', to='research.researchitem')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_items', to='research.researchrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('run', 'item'), name='unique_research_run_item')],
            },
        ),
    ]
