# Generated by Django 6.1.1 on 2026-10-07 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_researchrunitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchfinding',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='research.researchrun'),
        ),
    ]
