# Generated by Django 6.1.1 on 2026-10-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_researchfinding_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchfinding',
            name='content_opportunities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchfinding',
            name='limitations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researchfinding',
            name='related_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchfinding',
            name='why_it_matters',
            field=models.TextField(blank=True),
        ),
    ]
