# Generated by Django 6.1.1 on 2026-10-07 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_researchfinding_content_opportunities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchfinding',
            name='importance',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
