# Generated by Django 6.1.1 on 2026-10-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_researchfinding_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrun',
            name='depth',
            field=models.CharField(blank=True, choices=[('quick', 'Quick'), ('standard', 'Standard'), ('deep', 'Deep')], help_text='Research depth used for this run.', max_length=20, null=True),
        ),
    ]
