# Generated by Django 6.1.1 on 2026-10-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_researchrun_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
