# Generated by Django 6.1.1 on 2026-10-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_researchsource_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchfinding',
            name='supporting_items',
            field=models.ManyToManyField(blank=True, related_name='supporting_findings', to='research.researchitem'),
        ),
    ]
